data:
  file_path: "./val_set.mat"
  test_size: 0.15
  val_size: 0.15

training:
  batch_size: 32
  num_epochs: 300
  learning_rate: 0.0001
  patience: 10

logging:
  log_file: "training.log"
  log_level: "INFO"
  plot: False

checkpoint:
  save_path: "./checkpoints"
  monitor: "val_loss"
  mode: "min"
